### ISSUE TITLE
[Request] Hide Affixe Schedule!

### ISSUE THREAD

**Issue by RAtwood90** [Ermad/angry-keystones#15]
Hey Mate pls can you Add next Update an Option to Hide the Mythic Plus Affixe for the next Weeks?

![Unbenannt](https://user-images.githubusercontent.com/73589071/140324177-c3716924-d41a-4d8c-8df7-7ca9a1eb1dc6.png)

Regards!

**Comment by Ermad** [comment]
Yes, I'll make an option for this.

**Comment by Ermad** [comment]
Added in 24.1
