### ISSUE TITLE
compact raid frame error

### ISSUE THREAD

**Issue by Roneasaurus** [Ermad/angry-keystones#16]
Message: [ADDON_ACTION_BLOCKED] AddOn 'AngryKeystones' tried to call the protected function 'CompactRaidFrame1:Show()'.
Time: Thu Nov 18 14:00:16 2021
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'AngryKeystones' tried to call the protected function 'CompactRaidFrame1:Show()'.
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:307: in function `CompactUnitFrame_UpdateAll'
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:126: in function <Interface\FrameXML\CompactUnitFrame.lua:57>

Locals: <none>

version 0.22.1

**Comment by fgmenth** [comment]
This is duplicate of #14 . Check it out, I have a temporary solution there until the author fixes it.
