### ISSUE TITLE
Tazavesh keys are advertised wrong in the LFG tool

### ISSUE THREAD

**Issue by stx4** [Ermad/angry-keystones#21]
When starting a group in the LFG tool all fields are autofilled by Angry Keystones.
For Tazavesh Streets it autofills as Gambit and vice versa.

**Comment by Ermad** [comment]
Are you sure this is an Angry Keystones issue? Make sure it happens still when disabling Angry Keystones.

I didn't implement anything with LFG and Keystones, though could be a bug with another component interaction with it.

**Comment by stx4** [comment]
You’re right. I had disabled all addons except Angry Keystones and it was still happening.
So now I’ve disabled all addons including Angry Keystones and it also happens. Never knew the default Blizzard UI would automatically put the keystone advertisement up when clicking “Start a group”. Guess I’m reporting a bug there 😃

Sorry for the inconvenience.

Gr,

Stx

**Comment by stx4** [comment]
You’re right. I had disabled all addons except Angry Keystones and it was still happening.
So now I’ve disabled all addons including Angry Keystones and it also happens. Never knew the default Blizzard UI would automatically put the keystone advertisement up when clicking “Start a group”. Guess I’m reporting a bug there 😃
