### ISSUE TITLE
Create proper Github releases, please

### ISSUE THREAD

**Issue by marthammor** [Ermad/angry-keystones#23]
This is just a minor thing, but when you create releases could you also include a zip file with the release so that addon updaters that can update from GitHub can see the release and update properly?
There are options to create a zip and a tar.gz file through GitHub, but the updaters want a premade zip file apparently.  I've included a zip made through GitHub for the v0.24.1 tag if you'd like to use it and update the v0.24.1 release to include it as a binary.
[angry-keystones-0.24.1.zip](https://github.com/Ermad/angry-keystones/files/8634635/angry-keystones-0.24.1.zip)
This is important now that Curse is blocking addon updaters from seeing their information.
Thank you!

**Comment by KogasaPls** [comment]
+1, I would also appreciate this. The maintainers can set this up to happen automatically with https://github.com/BigWigsMods/packager

**Comment by Ermad** [comment]
I have also been adding releases to https://addons.wago.io/addons/angry-keystones for people to update outside of Overwolf. What Is the reason this is desired over those two options?

**Comment by marthammor** [comment]
I hadn't known about the wago option. Personally, that works just fine for me. I'm going to close this. Thanks!
