### ISSUE TITLE
Show objective tracker after Mythic Keystone completion????

### ISSUE THREAD

**Issue by wwbrandon** [Ermad/angry-keystones#28]
Hello,

I see on your description page saying there is an option for "Show objective tracker after Mythic Keystone completion" but I don't see this anywhere.

Would really love to use this feature. Where did it go? Am I overlooking it?

Best,

**Comment by Ermad** [comment]
I couldn’t find a way to implement it without causing taint issues, so I had to remove it.

**Comment by wwbrandon** [comment]
I'll accept any taint issue 100% to find a way to keep the scorecard up. lol
It blows my mind this isn't a native feature when completing a key...

Is there anyway you could look into this again? I'd happily do anything to compensate you for the work. Its the only thing my UI is missing. 

Best,

**Comment by Ermad** [comment]
It wasn't that it was just causing that popup that you could ignore, but it broke a decent bit of quest list functionality. Mostly the buttons related to world quests on the list.

Can take a look again to see if some if any of Blizzard code changed to make it possible, but I don't have an active sub atm so kind of limited in what I can change atm.

**Comment by wwbrandon** [comment]
I see. Admittedly, even when I looked up taint errors I didn't understand, but thanks for taking a look into this.

I've searched far and wide for a solution, but the only options out there involve unreliable substitutions. I want to stay with native if possible, just need it to stay on screen! I imagine this is something anyone who runs keys would want.

Thanks

**Comment by wwbrandon** [comment]
Hello! Wanted to ask if there have been any developments in DF that might allow this function again?

Thanks!

**Comment by wwbrandon** [comment]
Hello, wanted to bump this idea to see about getting this feature back. Do you remember which version you worked this code out of your addon? Perhaps I can just use an old version?

Doesn't bother me if I have taint issues.

**Comment by wwbrandon** [comment]
Hello again, 
What was the last version where the addon would hold the keystone timer on the screen? Really dying for this feature! 
Thanks!

**Comment by wwbrandon** [comment]
> I couldn’t find a way to implement it without causing taint issues, so I had to remove it.

Which version did you remove this feature? <3

**Comment by wwbrandon** [comment]
12.0 thank you
