### ISSUE TITLE
create Release Version @github

### ISSUE THREAD

**Issue by Polydoros95** [Ermad/angry-keystones#29]
Please create a Release Version to manage this addon with github

**Comment by Ermad** [comment]
Why is this desired over Curse/Wago?

**Comment by Polydoros95** [comment]
I use CurseBreaker to manage all addons in one program. GitHub releases are easy for CB to import and I'm not a fan of sites like Curse or Wago.

**Comment by Ermad** [comment]
Cursebreaker supports wago it looks like.
