### ISSUE TITLE
LUA Error: "tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'."

### ISSUE THREAD

**Issue by hightin** [Ermad/angry-keystones#32]
Started getting this recently and it has been spamming my chat window with odd errors mid key.

2x [ADDON_ACTION_BLOCKED] AddOn 'AngryKeystones' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:62: in function `SetPoint'
[string "@Interface/FrameXML/EditModeManager.lua"]:629: in function <Interface/FrameXML/EditModeManager.lua:608>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionButton.lua"]:373: in function `UpdateAction'
[string "@Interface/FrameXML/ActionButton.lua"]:803: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:216: in function <Interface/FrameXML/ActionButton.lua:213>

**Comment by madar2252** [comment]
Getting the same.
Running a few keys, let's say the first two keys are fine, and once the third dungeon begins, the lua errors are popping, counting to infinite, taking the focus, and then saying Angry Keystones causing too much trouble, do you want to disable it? 
Actually reloading UI solving the problem, works for another 2-3 keys, then same happening at the start of the dungeon. 
Lately I am just reloading the UI before every dungeon start to prevent the issue.

![1](https://user-images.githubusercontent.com/42252230/200609973-d4a5271d-8d31-4826-af63-5711778b2701.JPG)
![2](https://user-images.githubusercontent.com/42252230/200609989-3604e0f0-1a9f-417d-afc5-5e08972a0c3d.JPG)

**Comment by madar2252** [comment]
Looks like this is not happening if you use ElvUI. I guess some new Blizz UI stuff messing it up.
