### ISSUE TITLE
Error Auto Inserting Keystone

### ISSUE THREAD

**Issue by Evolutious** [Ermad/angry-keystones#41]
Good day! Thanks for the recent update; however I am getting the following error when I click on a keystone pedestal

`2x AngryKeystones/Keystone.lua:51: attempt to call global 'GetContainerNumSlots' (a nil value)`
`[string "@AngryKeystones/Keystone.lua"]:51: in function <AngryKeystones/Keystone.lua:49>`
`[string "=[C]"]: ?`
`[string "=[C]"]: in function 'Show'`
`[string "@Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua"]:652: in function '?'`
`[string "@FrameXML/UIParent.lua"]:2285: in function <FrameXML/UIParent.lua:1362>`
`[string "=[C]"]: in function 'CameraOrSelectOrMoveStop'`
`[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>`

`Locals:`
`(for index) = 0`
`(for limit) = 4`
`(for step) = 1`
`container = 0`
`(*temporary) = nil`
`(*temporary) = 0`
`(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"`

**Comment by Ermad** [comment]
Fixed in 26.3
