### ISSUE TITLE
Tooltip Background Missing

### ISSUE THREAD

**Issue by WowzaTO** [Ermad/angry-keystones#45]
Note: Cannot test this with Angry Keystones only. I had to at least load HandyNotes. When you right-click to access the menu, the background is gone. If I have only HandyNotes installed, background is there.

The error also happens with AK and WeakAura's only, right-click on a WeakAura, background will be gone. Without AK, everything is there.

![WoWScrnShot_112922_223558](https://user-images.githubusercontent.com/119471450/204925617-d56242ed-1f09-4bf5-9d16-46abe2db7619.jpg)

**Comment by Ermad** [comment]
I just released v0.26.5 with a possible fix, do you still get this issue with that?

**Comment by WowzaTO** [comment]
Just tested, this fixes that issue. Thanks.
