### ISSUE TITLE
Dragonflight S1 affix schedule is missing

### ISSUE THREAD

**Issue by madar2252** [Ermad/angry-keystones#46]
1 | Fortified | Raging | Quaking | Thundering
2 | Tyrannical | Bursting | Grievous | Thundering
3 | Fortified | Sanguine | Volcanic | Thundering
4 | Tyrannical | Raging | Storming | Thundering
5 | Fortified | Spiteful | Grievous | Thundering
6 | Tyrannical | Sanguine | Explosive | Thundering
7 | Fortified | Bolstering | Storming | Thundering
8 | Tyrannical | Spiteful | Quaking | Thundering
9 | Fortified | Bursting | Explosive | Thundering
10 | Tyrannical | Bolstering | Volcanic | Thundering

**Comment by Ermad** [comment]
Thanks, will be added in next release
