### ISSUE TITLE
Another too long dungeon names

### ISSUE THREAD

**Issue by madar2252** [Ermad/angry-keystones#47]
Shadowmoon Burial Grounds is too long for sure, but probably Temple of the Jade Serpent as well.

![image](https://user-images.githubusercontent.com/42252230/208243767-f733a9f7-cd5f-4cc5-94c2-e1fe2656fe48.png)

**Comment by willoucom** [comment]
Check PR #49

**Comment by willoucom** [comment]
Yes, i fixed it in the PR :)

**Comment by madar2252** [comment]
right, I can see in the PR screenshot! good job, thanks!

**Comment by Ermad** [comment]
I did a release with the changes.

Also added the ability to hard code in overrides for dungeon if desired, https://github.com/Ermad/angry-keystones/blob/master/Locale.lua#L50
