### ISSUE TITLE
The chest timers do not work

### ISSUE THREAD

**Issue by joelbb** [Ermad/angry-keystones#48]
I get only one timer, for the whole dungeon.  It no longer splits it into timers for 1, 2 and 3 chests.  I have completely uninstalled and reinstalled, and it still does not work.  It used to work, so I am not sure what happened.  I do have Astra Keys installed, the only other mythic+ related addon, but I do not believe there is a conflict.

**Comment by madar2252** [comment]
not sure what causing the problem at you, but for me it works

**Comment by Urganot** [comment]
Same issue for me
