### ISSUE TITLE
Add support for 10.1 Dungeon Affix rotation

### ISSUE THREAD

**Issue by rionshin** [Ermad/angry-keystones#53]
Could you please add support  for 10.1 Dungeon Affix rotation

Thanks

**Comment by EntOfMD** [comment]
Supposedly https://github.com/Ermad/angry-keystones/commit/727148fdf38be68d37c7d9d6f42e1ec916c8a239 should fix it, but i'm still having issues with it. `scheduleMissingKeystone = "Requires a level 7+ Mythic Keystone in your inventory to display"` is being displayed instead the schedule even though my keys are 15+
