### ISSUE TITLE
The mouse points to the next week affixes and receives an error

### ISSUE THREAD

**Issue by nanjuekaien1** [Ermad/angry-keystones#56]
...jectiveTracker/Blizzard_ScenarioObjectiveTracker.lua:473: Usage: GameTooltip:SetText("text" [, color, wrap])
Count: 2

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: in function `SetText'
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ScenarioObjectiveTracker.lua"]:473: in function <...jectiveTracker/Blizzard_ScenarioObjectiveTracker.lua:466>

**Comment by Grand-Warchief** [comment]
Can confirm I'm receiving this issue as well
