### ISSUE TITLE
Error with AngryKeystones

### ISSUE THREAD

**Issue by Sekorhex** [Ermad/angry-keystones#6]
2x AngryKeystones\Schedule.lua:116: attempt to index local 'legacyWeeklyChest' (a nil value)
[string "@AngryKeystones\Schedule.lua"]:116: in function <AngryKeystones\Schedule.lua:100>
[string "=[C]"]: in function `ChallengesFrame_Update'
[string "@Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:136: in function <...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:127>

Locals:
weeklyChest = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:336
 Highlight = <unnamed> {
 }
 Update = <function> defined @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:286
 OnMouseUp = <function> defined @FrameXML\WeeklyReward.lua:14
 HasUnlockedRewards = <function> defined @FrameXML\WeeklyReward.lua:3
 AnimTexture = <unnamed> {
 }
 state = 1
 RunStatus = <unnamed> {
 }
 Icon = <unnamed> {
 }
}
description = <unnamed> {
 0 = <userdata>
}
legacyWeeklyChest = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:336
 Highlight = <unnamed> {
 }
 Update = <function> defined @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:286
 OnMouseUp = <function> defined @FrameXML\WeeklyReward.lua:14
 HasUnlockedRewards = <function> defined @FrameXML\WeeklyReward.lua:3
 AnimTexture = <unnamed> {
 }
 state = 1
 RunStatus = <unnamed> {
 }
 Icon = <unnamed> {
 }
}
(*temporary) = "TOP"
(*temporary) = 0
(*temporary) = 75
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = 4
(*temporary) = nil
(*temporary) = nil
(*temporary) = 4
(*temporary) = 5
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'legacyWeeklyChest' (a nil value)"
Mod = <table> {
 CHALLENGE_MODE_UPDATED = <function> defined @AngryKeystones\Schedule.lua:432
 CHALLENGE_MODE_START = <function> defined @AngryKeystones\Schedule.lua:420
 AffixFrame = <unnamed> {
 }
 CheckCurrentKeystone = <function> defined @AngryKeystones\Schedule.lua:367
 SetPartyKeystoneRequest = <function> defined @AngryKeystones\Schedule.lua:353
 Blizzard_ChallengesUI = <function> defined @AngryKeystones\Schedule.lua:170
 KeystoneText = <unnamed> {
 }
 CheckAffixes = <function> defined @AngryKeystones\Schedule.lua:312
 SendCurrentKeystone = <function> defined @AngryKeystones\Schedule.lua:387
 PartyFrame = <unnamed> {
 }
 Startup = <function> defined @AngryKeystones\Schedule.lua:436
 GetInventoryKeystone = <function> defined @AngryKeystones\Schedule.lua:299
 CHALLENGE_MODE_COMPLETED = <function> defined @AngryKeystones\Schedule.lua:426
 CHAT_MSG_LOOT = <function> defined @AngryKeystones\Schedule.lua:342
 BAG_UPDATE = <function> defined @AngryKeystones\Schedule.lua:332
 SendPartyKeystonesRequest = <function> defined @AngryKeystones\Schedule.lua:361
 Name = "Schedule"
 ReceiveAddOnComm = <function> defined @AngryKeystones\Schedule.lua:399
}
GetNameForKeystone = <function> defined @AngryKeystones\Schedule.lua:30
Addon = <table> {
 ADDON_LOADED = <function> defined @AngryKeystones\Core.lua:47
 PLAYER_ENTERING_WORLD = <function> defined @AngryKeystones\Core.lua:218
 ForAllModules = <function> defined @AngryKeystones\Core.lua:209
 Modules = <table> {
 }
 ShortName = "AngryKeystones"
 CHAT_MSG_ADDON = <function> defined @AngryKeystones\Core.lua:156
 UnregisterAddOnComm = <function> defined @AngryKeystones\Core.lua:129
 RegisterEvent = <function> defined @AngryKeystones\Core.lua:18
 Version = "v0.19.8b"
 RegisterAddOnLoaded = <function> defined @AngryKeystones\Core.lua:59
 UnregisterAddOnLoaded = <function> defined @AngryKeystones\Core.lua:77
 Name = "Angry Keystones"
 NewModule = <function> defined @AngryKeystones\Core.lua:199
 SendAddOnComm = <function> defined @AngryKeystones\Core.lua:146
 ModulePrototype = <table> {
 }
 UnregisterEvent = <function> defined @AngryKeystones\Core.lua:94
 RegisterAddOnComm = <function> defined @Interf

**Comment by Ermad** [comment]
Fixed in v0.19.9
