### ISSUE TITLE
Not working with TWW pre-patch

### ISSUE THREAD

**Issue by Andf** [Ermad/angry-keystones#75]
Hello! I have just downloaded latest version (0.31.0) but addon is still not working and I receive some LUA errors when I try to open the configuration:

2x AngryKeystones/Config.lua:340: attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@AngryKeystones/Config.lua"]:340: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5449: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5395>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5101: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5100>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5137: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
msg = ""
editbox = ChatFrame1EditBox {
 tabCompleteTableIndex = 1
 at3matches = <table> {
 }
 focusLeft = ChatFrame1EditBoxFocusLeft {
 }
 focusRight = ChatFrame1EditBoxFocusRight {
 }
 pratFrame = Frame {
 }
 setText = 0
 chatFrame = ChatFrame1 {
 }
 addSpaceToAutoComplete = true
 languague = "Common"
 autoCompleteParams = <table> {
 }
 lDrag = Frame {
 }
 language = "Common"
 rDrag = Frame {
 }
 at3curMatch = 0
 focusMid = ChatFrame1EditBoxFocusMid {
 }
 headerSuffix = ChatFrame1EditBoxHeaderSuffix {
 }
 text = "/"
 header = ChatFrame1EditBoxHeader {
 }
 history_index = 0
 history_lines = <table> {
 }
 NewcomerHint = ChatFrame1EditBoxNewcomerHint {
 }
 addHighlightedText = true
 hookedByAceTab3 = true
 languageHeader = FontString {
 }
 languageID = 7
 prompt = ChatFrame1EditBoxPrompt {
 }
}
(*temporary) = nil
(*temporary) = Frame {
 name = "Angry Keystones"
}
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)"
optionPanel = Frame {
 name = "Angry Keystones"
}

**Comment by Ermad** [comment]
Fixed in next release

**Comment by Andf** [comment]
Many thanks!
