### ISSUE TITLE
Exact Mythic+ Mob Count Values No Longer Trackable Via Addons in War Within

### ISSUE THREAD

**Issue by nanjuekaien1** [Ermad/angry-keystones#77]
Just saw it.
Exact Mythic+ Mob Count Values No Longer Trackable Via Addons in War Within
https://www.wowhead.com/news/exact-mythic-mob-count-values-no-longer-trackable-via-addons-in-war-within-345848

**Comment by jere-software** [comment]
I saw this and wondered if this is what is causing Angry Keystones to not show dungeon count on the bar.  The only thing giving me pause is that AngryKeystones was updated post this change, but there is still an option in the addon to do that display, so I don't know if it is:

a. Above issue and addon options for display aren't updated to reflect the option no longer works
or
b. A work around for the above issue was found (convert from % to count, death tracking, etc.) and my UI is borked and doesn't show it.

I'm not getting any lua errors making me think lack of dungeon count is causing an issue for the addon (with errors display turned on).

**Comment by CruelDrool** [comment]
Issue was that the returned table from `C_ScenarioInfo.GetCriteriaInfo` didn't contain the field "quantityString". [That was fixed](https://github.com/Stanzilla/WoWUIBugs/issues/592#issuecomment-2294437578) a few hours ago.  I'm testing out some code for this [here](https://github.com/Ermad/angry-keystones/issues/73#issuecomment-2294624472).

**Comment by jere-software** [comment]
Thanks for the update!
