### ISSUE TITLE
Lua error with Kaliel Tracker

### ISSUE THREAD

**Issue by AngelosNaoumis** [Ermad/angry-keystones#79]
9x AngryKeystones/ObjectiveTracker.lua:131: hooksecurefunc(): KT_Scenario_ChallengeMode_UpdateTime is not a function

[string "=[C]"]: in function `hooksecurefunc'

[string "@AngryKeystones/ObjectiveTracker.lua"]:131: in main chunk

 

Locals:

**Comment by shisva** [comment]
Have the same issue but this error :

`
Message: Interface/AddOns/AngryKeystones/ObjectiveTracker.lua:131: hooksecurefunc(): KT_Scenario_ChallengeMode_UpdateTime is not a function
Time: Mon Aug 26 21:20:11 2024
Count: 1
Stack: Interface/AddOns/AngryKeystones/ObjectiveTracker.lua:131: hooksecurefunc(): KT_Scenario_ChallengeMode_UpdateTime is not a function

Locals: 
`

**Comment by Ermad** [comment]
Fixed in latest release
