### ISSUE TITLE
attempt to index field 'NewFeature' (a nil value) error when opening Options menu since 11.0.5

### ISSUE THREAD

**Issue by denumerable** [Ermad/angry-keystones#87]
Message: ...ystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)
Time: Wed Nov  6 21:37:47 2024
Count: 1
Stack: ...ystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)
[string "@Interface/AddOns/Blizzard_SharedXMLBase/ErrorUtil.lua"]:3: in function <...nterface/AddOns/Blizzard_SharedXMLBase/ErrorUtil.lua:1>
[string "@Interface/AddOns/AngryKeystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1512: in function `UIDropDownMenu_Refresh'
[string "@Interface/AddOns/AngryKeystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1580: in function `UIDropDownMenu_SetSelectedValue'
[string "@Interface/AddOns/AngryKeystones/Config.lua"]:299: in function `OnRefresh'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:9: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:7>
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:514: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:513>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:477: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:474>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:485: in function `ForEachCanvas'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:513: in function `CallRefreshOnCanvases'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:169: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:135>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:493: in function `SetUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:295: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:174: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:169>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:893: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:262: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:260>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Blizzard_GameMenu/Standard/GameMenuFrame.lua"]:68: in function <.../AddOns/Blizzard_GameMenu/Standard/GameMenuFrame.lua:65>

Locals: 

Message: ...ystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)
Time: Wed Nov  6 21:42:41 2024
Count: 2
Stack: ...ystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/AngryKeystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1512: in function `UIDropDownMenu_Refresh'
[string "@Interface/AddOns/AngryKeystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1580: in function `UIDropDownMenu_SetSelectedValue'
[string "@Interface/AddOns/AngryKeystones/Config.lua"]:299: in function `OnRefresh'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:9: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:7>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:864: in function `DisplayLayout'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:807: in function `DisplayCategory'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:749: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:742>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_CategoryList.lua"]:152: in function <...s/Blizzard_Settings_Shared/Blizzard_CategoryList.lua:150>

Locals:

**Comment by Ermad** [comment]
Just released v0.31.8 which should fix it

**Comment by denumerable** [comment]
Thank you, @Ermad! <3
